public enum ResourceCost
{
    Wood,
    Hide,
    TwoWood,
    TwoHide,
    ThreeHide,
    ThreeWood,
    FourWood,
    FiveWood,
    TwoWoodOrHide,
    ThreeWoodOrTwoHide,
    FourWoodOrThreeHide,
    WoodUnlessShovel,
    ReducedToZero,
    WoodOrHide,
    TwoWoodOrTwoHide,
    ThreeWoodOrThreeHide,
    Food
}
